sources:
  - name: NotionalV3
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/33671/notional-finance-v3-{context.chainName:arbitrum}/v0.1.19

documents:
  - ./queries/*.graphql

codegen:
  contextType: 'MeshContext & { chainName: string }'