sources:
  - name: NotionalExponent
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/60626/notional-exponent/version/latest
        retry: 2

documents:
  - ./queries/*.graphql

codegen:
  contextType: 'MeshContext & { apiKey: string, subgraphId: string, network: string }'
