sources:
  - name: NotionalV3
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/36749/notional-finance-v3-{context.chainName:arbitrum}/version/latest

documents:
  - ./queries/*.graphql

codegen:
  contextType: 'MeshContext & { chainName: string }'