sources:
  - name: NotionalExponent
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/60626/notional-exponent/version/latest
        # endpoint: https://gateway.thegraph.com/api/subgraphs/id/9fw42E6QrezaPxixKN9H79nWmpVWURkLmcJdgGHyC14B
        operationHeaders:
          Authorization: Bearer {context.apiKey}
        retry: 2

documents:
  - ./src/queries/*.graphql

codegen:
  contextType: 'MeshContext & { apiKey: string, subgraphId: string, network: string }'
