sources:
  - name: NotionalV3
    handler:
      graphql:
        endpoint: https://gateway-arbitrum.network.thegraph.com/api/{context.apiKey:env.NX_SUBGRAPH_API_KEY}/subgraphs/id/{context.subgraphId:4oVxkMtN4cFepbiYrSKz1u6HWnJym435k5DQRAFt2vHW}

documents:
  - ./queries/*.graphql

codegen:
  contextType: 'MeshContext & { apiKey: string, subgraphId: string }'