sources:
  - name: NotionalV3
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/33671/notional-finance-v3-{context.chainName:arbitrum}/v0.0.54
    transforms:
      - blockTracking:
          # Disabled for faster initial loading
          validateSchema: false
      - autoPagination:
          # Disabled for faster initial loading
          validateSchema: false

documents:
  - ./src/queries/AllTokens.graphql

codegen:
  contextType: 'MeshContext & { chainName: string }'