/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type MarketParamsStruct = {
  loanToken: PromiseOrValue<string>;
  collateralToken: PromiseOrValue<string>;
  oracle: PromiseOrValue<string>;
  irm: PromiseOrValue<string>;
  lltv: PromiseOrValue<BigNumberish>;
};

export type MarketParamsStructOutput = [
  string,
  string,
  string,
  string,
  BigNumber
] & {
  loanToken: string;
  collateralToken: string;
  oracle: string;
  irm: string;
  lltv: BigNumber;
};

export type MarketStruct = {
  totalSupplyAssets: PromiseOrValue<BigNumberish>;
  totalSupplyShares: PromiseOrValue<BigNumberish>;
  totalBorrowAssets: PromiseOrValue<BigNumberish>;
  totalBorrowShares: PromiseOrValue<BigNumberish>;
  lastUpdate: PromiseOrValue<BigNumberish>;
  fee: PromiseOrValue<BigNumberish>;
};

export type MarketStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  totalSupplyAssets: BigNumber;
  totalSupplyShares: BigNumber;
  totalBorrowAssets: BigNumber;
  totalBorrowShares: BigNumber;
  lastUpdate: BigNumber;
  fee: BigNumber;
};

export interface MorphoAdaptiveIRMInterface extends utils.Interface {
  functions: {
    "MORPHO()": FunctionFragment;
    "borrowRate((address,address,address,address,uint256),(uint128,uint128,uint128,uint128,uint128,uint128))": FunctionFragment;
    "borrowRateView((address,address,address,address,uint256),(uint128,uint128,uint128,uint128,uint128,uint128))": FunctionFragment;
    "rateAtTarget(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MORPHO"
      | "borrowRate"
      | "borrowRateView"
      | "rateAtTarget"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "MORPHO", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrowRate",
    values: [MarketParamsStruct, MarketStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowRateView",
    values: [MarketParamsStruct, MarketStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "rateAtTarget",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(functionFragment: "MORPHO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "borrowRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowRateView",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rateAtTarget",
    data: BytesLike
  ): Result;

  events: {
    "BorrowRateUpdate(bytes32,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BorrowRateUpdate"): EventFragment;
}

export interface BorrowRateUpdateEventObject {
  id: string;
  avgBorrowRate: BigNumber;
  rateAtTarget: BigNumber;
}
export type BorrowRateUpdateEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  BorrowRateUpdateEventObject
>;

export type BorrowRateUpdateEventFilter =
  TypedEventFilter<BorrowRateUpdateEvent>;

export interface MorphoAdaptiveIRM extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MorphoAdaptiveIRMInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MORPHO(overrides?: CallOverrides): Promise<[string]>;

    borrowRate(
      marketParams: MarketParamsStruct,
      market: MarketStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    borrowRateView(
      marketParams: MarketParamsStruct,
      market: MarketStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    rateAtTarget(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  MORPHO(overrides?: CallOverrides): Promise<string>;

  borrowRate(
    marketParams: MarketParamsStruct,
    market: MarketStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  borrowRateView(
    marketParams: MarketParamsStruct,
    market: MarketStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  rateAtTarget(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    MORPHO(overrides?: CallOverrides): Promise<string>;

    borrowRate(
      marketParams: MarketParamsStruct,
      market: MarketStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    borrowRateView(
      marketParams: MarketParamsStruct,
      market: MarketStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateAtTarget(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "BorrowRateUpdate(bytes32,uint256,uint256)"(
      id?: PromiseOrValue<BytesLike> | null,
      avgBorrowRate?: null,
      rateAtTarget?: null
    ): BorrowRateUpdateEventFilter;
    BorrowRateUpdate(
      id?: PromiseOrValue<BytesLike> | null,
      avgBorrowRate?: null,
      rateAtTarget?: null
    ): BorrowRateUpdateEventFilter;
  };

  estimateGas: {
    MORPHO(overrides?: CallOverrides): Promise<BigNumber>;

    borrowRate(
      marketParams: MarketParamsStruct,
      market: MarketStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    borrowRateView(
      marketParams: MarketParamsStruct,
      market: MarketStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    rateAtTarget(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MORPHO(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    borrowRate(
      marketParams: MarketParamsStruct,
      market: MarketStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    borrowRateView(
      marketParams: MarketParamsStruct,
      market: MarketStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    rateAtTarget(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
