name = "notional-web-v4"
compatibility_date = "2025-06-09"
main = "./worker/index.ts"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "../../dist/apps/web"
not_found_handling = "single-page-application"
binding = "ASSETS"
run_worker_first = true

[[r2_buckets]]
binding = "VIEW_CACHE_R2"
bucket_name = "view-cache-r2-dev"
preview_bucket_name = "view-cache-r2-dev"

[env.prod]
name = "notional-web-v4"
r2_buckets = [
    { binding = "VIEW_CACHE_R2", bucket_name = "view-cache-r2-dev", preview_bucket_name = "view-cache-r2-dev" },
]

[env.dev]
name = "notional-web-v4-dev"
r2_buckets = [
    { binding = "VIEW_CACHE_R2", bucket_name = "view-cache-r2-dev", preview_bucket_name = "view-cache-r2-dev" },
]
