main = "./src/index.ts"
compatibility_date = "2022-11-11"

workers_dev = true
node_compat = true
minify = true
logpush = true


[[migrations]]
tag = "v1"
new_classes = [ "OracleRegistryDO" ]

[env.dev]
name = "registry-oracles-dev"

[env.dev.vars]
NX_ENV = 'dev'
# This is version that defines the durable object to retreive, increment it to reset
# the durable object to a clean version
VERSION = 'v1'
SUPPORTED_NETWORKS = [ 'arbitrum', 'all' ]

# NX_DD_API_KEY

[env.dev.durable_objects]
bindings = [
  { name = "ORACLE_REGISTRY_DO", class_name = "OracleRegistryDO" },
]

