import {
  ContestTableColumn,
  customIconCell,
  addressCell,
  idCell,
} from '@notional-finance/mui';

export const useLeaderBoardTables = () => {
  const leaderBoardColumns: ContestTableColumn[] = [
    {
      Header: '',
      accessor: 'id',
      Cell: idCell,
      isIDCell: true,
      textAlign: 'center',
      width: '76px',
    },
    {
      Header: '',
      Cell: customIconCell,
      accessor: 'username',
      textAlign: 'left',
    },
    {
      Header: 'Total APY',
      accessor: 'totalAPY',
      textAlign: 'right',
    },
    {
      Header: 'Leverage',
      accessor: 'leverage',
      textAlign: 'right',
    },
    {
      Header: 'Total Deposits',
      accessor: 'totalDeposits',
      textAlign: 'right',
    },
    {
      Header: 'Net Worth',
      accessor: 'netWorth',
      textAlign: 'right',
    },
    {
      Header: 'Total Earnings',
      accessor: 'totalEarnings',
      textAlign: 'right',
    },
    {
      Header: 'View Portfolio',
      accessor: 'viewPortfolio',
      Cell: addressCell,
      textAlign: 'right',
    },
  ];

  const currentUserColumns = leaderBoardColumns.filter(
    ({ accessor }) => accessor !== 'viewPortfolio'
  );

  const currentUserData = [
    {
      id: '04',
      username: { text: 'Some guy', dataSet: 'ace' },
      totalAPY: '63.21% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
    },
  ];

  const aceData = [
    {
      id: '01',
      username: { text: 'John Doe', dataSet: 'ace' },
      totalAPY: '63.21% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '02',
      username: { text: 'Jane Doe', dataSet: 'ace' },
      totalAPY: '44.17% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '03',
      username: { text: 'Peter Smith', dataSet: 'ace' },
      totalAPY: '98.73% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '04',
      username: { text: 'Susan Jones', dataSet: 'ace' },
      totalAPY: '19.04% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '05',
      username: { text: 'Michael Brown', dataSet: 'ace' },
      totalAPY: '55.38% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '06',
      username: {
        text: 'Emma White',
        dataSet: 'ace',
      },
      totalAPY: '34.56% APY',
      leverage: 'Yes',
      totalDeposits: '$90,000',
      netWorth: '$105,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '07',
      username: {
        text: 'William Brown',
        dataSet: 'ace',
      },
      totalAPY: '23.45% APY',
      leverage: 'Yes',
      totalDeposits: '$70,000',
      netWorth: '$85,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '08',
      username: {
        text: 'Elizabeth Green',
        dataSet: 'ace',
      },
      totalAPY: '78.90% APY',
      leverage: 'Yes',
      totalDeposits: '$100,000',
      netWorth: '$125,000',
      totalEarnings: '$25,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '09',
      username: {
        text: 'Danielle Williams',
        dataSet: 'ace',
      },
      totalAPY: '56.78% APY',
      leverage: 'Yes',
      totalDeposits: '$60,000',
      netWorth: '$75,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '10',
      username: {
        text: 'Michael Thomas',
        dataSet: 'ace',
      },
      totalAPY: '45.67% APY',
      leverage: 'Yes',
      totalDeposits: '$85,000',
      netWorth: '$100,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '11',
      username: {
        text: 'David Williams',
        dataSet: 'ace',
      },
      totalAPY: '46.78% APY',
      leverage: 'Yes',
      totalDeposits: '$75,000',
      netWorth: '$90,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '12',
      username: {
        text: 'Jennifer Jones',
        dataSet: 'ace',
      },
      totalAPY: '67.89% APY',
      leverage: 'Yes',
      totalDeposits: '$95,000',
      netWorth: '$110,000',
      totalEarnings: '$20,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '13',
      username: {
        text: 'Mark Smith',
        dataSet: 'ace',
      },
      totalAPY: '17.89% APY',
      leverage: 'Yes',
      totalDeposits: '$65,000',
      netWorth: '$75,000',
      totalEarnings: '$10,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '14',
      username: {
        text: 'Sarah Brown',
        dataSet: 'ace',
      },
      totalAPY: '36.78% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '15',
      username: {
        text: 'Steven Williams',
        dataSet: 'ace',
      },
      totalAPY: '57.89% APY',
      leverage: 'Yes',
      totalDeposits: '$60,000',
      netWorth: '$75,000',
      totalEarnings: '$10,000',
      viewPortfolio: '0xf9f2...123A',
    },
  ];

  const fatCatData = [
    {
      id: '01',
      username: { text: 'John Doe', dataSet: 'fatCat' },
      totalAPY: '63.21% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '02',
      username: { text: 'Jane Doe', dataSet: 'fatCat' },
      totalAPY: '44.17% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '03',
      username: { text: 'Peter Smith', dataSet: 'fatCat' },
      totalAPY: '98.73% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '04',
      username: { text: 'Susan Jones', dataSet: 'fatCat' },
      totalAPY: '19.04% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '05',
      username: { text: 'Michael Brown', dataSet: 'fatCat' },
      totalAPY: '55.38% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '06',
      username: {
        text: 'Emma White',
        dataSet: 'fatCat',
      },
      totalAPY: '34.56% APY',
      leverage: 'Yes',
      totalDeposits: '$90,000',
      netWorth: '$105,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '07',
      username: {
        text: 'William Brown',
        dataSet: 'fatCat',
      },
      totalAPY: '23.45% APY',
      leverage: 'Yes',
      totalDeposits: '$70,000',
      netWorth: '$85,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '08',
      username: {
        text: 'Elizabeth Green',
        dataSet: 'fatCat',
      },
      totalAPY: '78.90% APY',
      leverage: 'Yes',
      totalDeposits: '$100,000',
      netWorth: '$125,000',
      totalEarnings: '$25,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '09',
      username: {
        text: 'Danielle Williams',
        dataSet: 'fatCat',
      },
      totalAPY: '56.78% APY',
      leverage: 'Yes',
      totalDeposits: '$60,000',
      netWorth: '$75,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '10',
      username: {
        text: 'Michael Thomas',
        dataSet: 'fatCat',
      },
      totalAPY: '45.67% APY',
      leverage: 'Yes',
      totalDeposits: '$85,000',
      netWorth: '$100,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '11',
      username: {
        text: 'David Williams',
        dataSet: 'fatCat',
      },
      totalAPY: '46.78% APY',
      leverage: 'Yes',
      totalDeposits: '$75,000',
      netWorth: '$90,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '12',
      username: {
        text: 'Jennifer Jones',
        dataSet: 'fatCat',
      },
      totalAPY: '67.89% APY',
      leverage: 'Yes',
      totalDeposits: '$95,000',
      netWorth: '$110,000',
      totalEarnings: '$20,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '13',
      username: {
        text: 'Mark Smith',
        dataSet: 'fatCat',
      },
      totalAPY: '17.89% APY',
      leverage: 'Yes',
      totalDeposits: '$65,000',
      netWorth: '$75,000',
      totalEarnings: '$10,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '14',
      username: {
        text: 'Sarah Brown',
        dataSet: 'fatCat',
      },
      totalAPY: '36.78% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '15',
      username: {
        text: 'Steven Williams',
        dataSet: 'fatCat',
      },
      totalAPY: '57.89% APY',
      leverage: 'Yes',
      totalDeposits: '$60,000',
      netWorth: '$75,000',
      totalEarnings: '$10,000',
      viewPortfolio: '0xf9f2...123A',
    },
  ];

  const sadSackData = [
    {
      id: '01',
      username: { text: 'John Doe', dataSet: 'sadSack' },
      totalAPY: '63.21% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '02',
      username: { text: 'Jane Doe', dataSet: 'sadSack' },
      totalAPY: '44.17% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '03',
      username: { text: 'Peter Smith', dataSet: 'sadSack' },
      totalAPY: '98.73% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '04',
      username: { text: 'Susan Jones', dataSet: 'sadSack' },
      totalAPY: '19.04% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '05',
      username: { text: 'Michael Brown', dataSet: 'sadSack' },
      totalAPY: '55.38% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '06',
      username: {
        text: 'Emma White',
        dataSet: 'sadSack',
      },
      totalAPY: '34.56% APY',
      leverage: 'Yes',
      totalDeposits: '$90,000',
      netWorth: '$105,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '07',
      username: {
        text: 'William Brown',
        dataSet: 'sadSack',
      },
      totalAPY: '23.45% APY',
      leverage: 'Yes',
      totalDeposits: '$70,000',
      netWorth: '$85,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '08',
      username: {
        text: 'Elizabeth Green',
        dataSet: 'sadSack',
      },
      totalAPY: '78.90% APY',
      leverage: 'Yes',
      totalDeposits: '$100,000',
      netWorth: '$125,000',
      totalEarnings: '$25,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '09',
      username: {
        text: 'Danielle Williams',
        dataSet: 'sadSack',
      },
      totalAPY: '56.78% APY',
      leverage: 'Yes',
      totalDeposits: '$60,000',
      netWorth: '$75,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '10',
      username: {
        text: 'Michael Thomas',
        dataSet: 'sadSack',
      },
      totalAPY: '45.67% APY',
      leverage: 'Yes',
      totalDeposits: '$85,000',
      netWorth: '$100,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '11',
      username: {
        text: 'David Williams',
        dataSet: 'sadSack',
      },
      totalAPY: '46.78% APY',
      leverage: 'Yes',
      totalDeposits: '$75,000',
      netWorth: '$90,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '12',
      username: {
        text: 'Jennifer Jones',
        dataSet: 'sadSack',
      },
      totalAPY: '67.89% APY',
      leverage: 'Yes',
      totalDeposits: '$95,000',
      netWorth: '$110,000',
      totalEarnings: '$20,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '13',
      username: {
        text: 'Mark Smith',
        dataSet: 'sadSack',
      },
      totalAPY: '17.89% APY',
      leverage: 'Yes',
      totalDeposits: '$65,000',
      netWorth: '$75,000',
      totalEarnings: '$10,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '14',
      username: {
        text: 'Sarah Brown',
        dataSet: 'sadSack',
      },
      totalAPY: '36.78% APY',
      leverage: 'Yes',
      totalDeposits: '$80,000',
      netWorth: '$95,000',
      totalEarnings: '$15,000',
      viewPortfolio: '0xf9f2...123A',
    },
    {
      id: '15',
      username: {
        text: 'Steven Williams',
        dataSet: 'sadSack',
      },
      totalAPY: '57.89% APY',
      leverage: 'Yes',
      totalDeposits: '$60,000',
      netWorth: '$75,000',
      totalEarnings: '$10,000',
      viewPortfolio: '0xf9f2...123A',
    },
  ];

  return {
    leaderBoardColumns,
    currentUserData,
    currentUserColumns,
    aceData,
    fatCatData,
    sadSackData,
  };
};
