main = "./src/index.ts"
compatibility_date = "2022-11-11"
account_id = "274f86c6dcfbb77c09e49e86d101c753"
tsconfig = "./tsconfig.app.json"
usage_model = "bundled"

workers_dev = true
node_compat = true
minify = true

[triggers]
crons = [
    "*/10 * * * *",
    "0 0 * * *"
]

[env.dev]
name = "system-cache-dev"
[env.dev.vars]
NX_ENV = "dev"
VERSION = "v2"
SUPPORTED_CHAINS = ['mainnet']

[env.dev.durable_objects]
bindings = [
  { name = "SYSTEM_CACHE", class_name = "SystemCache", script_name = "system-cache-dev" }
]

[[env.dev.r2_buckets]]
binding = "VAULT_RETURNS"
bucket_name = "vault-returns"
preview_bucket_name = "vault-returns-dev"

[[env.dev.migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["SystemCache"]

[env.beta]
name = "system-cache-beta"

[env.beta.vars]
NX_ENV = "beta"
VERSION = "v2"
SUPPORTED_CHAINS = ['mainnet']

[env.beta.durable_objects]
bindings = [
  { name = "SYSTEM_CACHE", class_name = "SystemCache", script_name = "system-cache-beta" }
]

[[env.beta.r2_buckets]]
binding = "VAULT_RETURNS"
bucket_name = "vault-returns"

[[env.beta.migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["SystemCache"]
