main = "./src/index.ts"
compatibility_date = "2024-05-01"
account_id = "274f86c6dcfbb77c09e49e86d101c753"

logpush = true
workers_dev = true
node_compat = true
minify = true

[[migrations]]
tag = "v1"
new_classes = [
    "ExchangeRegistryDO",
]

[triggers]
crons = ["* * * * *"]

[env.dev]
name = "registry-exchanges-dev"

[env.dev.vars]
NX_ENV = 'dev'
# This is version that defines the durable object to retreive, increment it to reset
# the durable object to a clean version
VERSION = 'v1'
NX_DATA_URL = 'https://data-dev.notional.finance'
SUPPORTED_NETWORKS = [ 'arbitrum', 'all', 'mainnet' ]

[env.dev.durable_objects]
bindings = [
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO" }
]


[env.prod]
name = "registry-exchange"

[env.prod.vars]
NX_ENV = 'prod'
VERSION = 'v1'
NX_DATA_URL = 'https://data.notional.finance'
SUPPORTED_NETWORKS = [ 'arbitrum', 'all' ]

[env.prod.durable_objects]
bindings = [
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO" },
  { name = "ORACLE_REGISTRY_DO", class_name = "OracleRegistryDO" },
]