main = "./src/index.ts"
compatibility_date = "2022-11-11"
account_id = "274f86c6dcfbb77c09e49e86d101c753"

logpush = true
workers_dev = true
node_compat = true
minify = true
usage_model = "unbound"

[[migrations]]
tag = "v1"
new_classes = [
    "ExchangeRegistryDO",
]

[env.local]
name = "registry-exchange-local"
minify = false

[env.local.vars]
NX_ENV = 'local'
VERSION = 'v1'
NX_DATA_URL = 'https://data-dev.notional.finance'
SUPPORTED_NETWORKS = ['arbitrum', 'all']

[env.local.durable_objects]
bindings = [
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO" },
]

[env.dev]
name = "registry-exchange-dev"

[env.dev.vars]
NX_ENV = 'dev'
# This is version that defines the durable object to retreive, increment it to reset
# the durable object to a clean version
VERSION = 'v1'
NX_DATA_URL = 'https://data-dev.notional.finance'
SUPPORTED_NETWORKS = [ 'arbitrum', 'all' ]

[env.dev.durable_objects]
bindings = [
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO" },
]


[env.prod]
name = "registry-exchange"

[env.prod.vars]
NX_ENV = 'prod'
VERSION = 'v1'
NX_DATA_URL = 'https://data.notional.finance'
SUPPORTED_NETWORKS = [ 'arbitrum', 'all' ]

[env.prod.durable_objects]
bindings = [
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO" },
]