main = "./src/index.ts"
compatibility_date = "2025-08-08"

workers_dev = true
compatibility_flags = ["nodejs_compat"]
minify = true
logpush = true


[env.dev]
name = "<%= name %>-dev"

[env.prod]
name = "<%= name %>"
