main = "./src/index.ts"
compatibility_date = "2022-11-11"

workers_dev = true
logpush = true
minify = true

[triggers]
crons = ["0/2 * * * *"]

[env.mainnet]
name = "exponent-liquidator-mainnet"

[env.mainnet.vars]
MORPHO_LENDING_ROUTER_ADDRESS = '0x9a0c630c310030c4602d1a76583a3b16972ecaa0'
FLASH_LIQUIDATOR_ADDRESS = '0x3d3DD434c6fd94FBd20e1d0649595Cc7612fFBeB'
TRADING_MODULE_ADDRESS = '0x594734c7e06C3D483466ADBCe401C6Bd269746C8'
NETWORK = 'mainnet'
LOG_LEVEL = 'info'

[env.arbitrum]
name = "exponent-liquidator-arbitrum"

[env.arbitrum.vars]
MORPHO_LENDING_ROUTER_ADDRESS = '0x0000000000000000000000000000000000000000'
NETWORK = 'arbitrum'
LOG_LEVEL = 'info'