main = "./src/index.ts"
compatibility_date = "2022-11-11"

workers_dev = true
logpush = true
minify = true

[triggers]
crons = ["0/2 * * * *"]

[env.mainnet]
name = "exponent-liquidator-mainnet"

[env.mainnet.vars]
DATA_SERVICE_URL = 'https://example.com/api/accounts'
MORPHO_LENDING_ROUTER_ADDRESS = '0x9a0c630c310030c4602d1a76583a3b16972ecaa0'
FLASH_LIQUIDATOR_ADDRESS = '0xD77Ce5587e0dd3b9239C8c0836a3Dc47b9188ACd'
TRADING_MODULE_ADDRESS = '0x594734c7e06C3D483466ADBCe401C6Bd269746C8'
NETWORK = 'mainnet'

[env.arbitrum] 
name = "exponent-liquidator-arbitrum"

[env.arbitrum.vars]
DATA_SERVICE_URL = 'https://example.com/api/accounts'
MORPHO_LENDING_ROUTER_ADDRESS = '0x0000000000000000000000000000000000000000'
NETWORK = 'arbitrum'