runtime: custom
env: flex
service: data-service

manual_scaling:
  instances: 1

 #[START gae_flex_pubsub_yaml]
env_variables:
  DB_USER: postgres
  DB_NAME: notional-v3
  DB_HOST: /cloudsql/monitoring-agents:us-central1:notional
  REGISTRY_URL: https://registry.notional.finance
  SERVICE_PORT: 8080
  MERGE_CONFLICTS: 'false'
  NX_USE_CROSS_FETCH: 'true'
  CLOUDFLARE_ACCOUNT_ID: 274f86c6dcfbb77c09e49e86d101c753
  R2_ACCESS_KEY_ID: 09f2809bc45eba2e05cf8cf7cb91a269
  # Secrets
  DB_PASS: "projects/663932775145/secrets/DB_PASS/versions/latest"
  DATA_SERVICE_AUTH_TOKEN: "projects/663932775145/secrets/DATA_SERVICE_AUTH_TOKEN/versions/latest"
  R2_SECRET_ACCESS_KEY: "projects/663932775145/secrets/R2_SECRET_ACCESS_KEY/versions/latest"
  DUNE_API_KEY: "projects/663932775145/secrets/DUNE_API_KEY/versions/latest"
  SUBGRAPH_API_KEY: "projects/663932775145/secrets/SUBGRAPH_API_KEY/versions/latest"
  DD_API_KEY: "projects/663932775145/secrets/DD_API_KEY/versions/latest"
#[END gae_flex_pubsub_yaml]

# Add liveness health check configuration
liveness_check:
  path: "/healthz"  # Replace with your actual health check endpoint
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 2
  success_threshold: 2

beta_settings:
  cloud_sql_instances: monitoring-agents:us-central1:notional

