main = "./src/index.ts"
compatibility_date = "2022-11-11"
account_id = "274f86c6dcfbb77c09e49e86d101c753"

workers_dev = true
node_compat = true
minify = true
usage_model = "bundled"
tsconfig = "tsconfig.json"

[env.local]
name = "api-local"
minify = false
durable_objects.bindings = [
  { name = "KPIS_DO", class_name = "KPIsDO" },
  { name = "ACCOUNTS_DO", class_name = "AccountsDO" },
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO", script_name = "registry-exchange-dev" },
  { name = "CONFIGURATION_REGISTRY_DO", class_name = "ConfigurationRegistryDO", script_name = "registry-dev" },
  { name = "ORACLE_REGISTRY_DO", class_name = "OracleRegistryDO", script_name = "registry-dev" },
  { name = "TOKEN_REGISTRY_DO", class_name = "TokenRegistryDO", script_name = "registry-dev" },
  { name = "VAULT_REGISTRY_DO", class_name = "VaultRegistryDO", script_name = "registry-dev" },
  { name = "YIELD_REGISTRY_DO", class_name = "YieldRegistryDO", script_name = "data-dev" },
  { name = "VIEWS_DO", class_name = "ViewsDO", script_name = "data-dev" }
]

[env.local.vars]
NX_ENV = "local"
VERSION = "v2"
KPIS_NAME = "KPIS_DO"
ACCOUNTS_NAME = "ACCOUNTS_DO"
VIEWS_NAME = "VIEWS_DO"

[env.dev]
name = "api-dev"
route = { pattern = "data-dev.notional.finance", custom_domain = true }
durable_objects.bindings = [
  { name = "KPIS_DO", class_name = "KPIsDO" },
  { name = "ACCOUNTS_DO", class_name = "AccountsDO" },
  { name = "CONFIGURATION_REGISTRY_DO", class_name = "ConfigurationRegistryDO", script_name = "registry-dev" },
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO", script_name = "registry-exchange-dev" },
  { name = "ORACLE_REGISTRY_DO", class_name = "OracleRegistryDO", script_name = "registry-dev" },
  { name = "TOKEN_REGISTRY_DO", class_name = "TokenRegistryDO", script_name = "registry-dev" },
  { name = "VAULT_REGISTRY_DO", class_name = "VaultRegistryDO", script_name = "registry-dev" },
  { name = "YIELD_REGISTRY_DO", class_name = "YieldRegistryDO", script_name = "data-dev" },
  { name = "VIEWS_DO", class_name = "ViewsDO", script_name = "data-dev" }
]

[env.dev.vars]
NX_ENV = "dev"
# This is version that defines the durable object to retreive, increment it to reset
# the durable object to a clean version
VERSION = "v4"
KPIS_NAME = "KPIS_DO"
ACCOUNTS_NAME = "ACCOUNTS_DO"
VIEWS_NAME = "VIEWS_DO"

[env.prod]
name = "api"
route = { pattern = "data.notional.finance", custom_domain = true }
durable_objects.bindings = [
  { name = "KPIS_DO", class_name = "KPIsDO" },
  { name = "ACCOUNTS_DO", class_name = "AccountsDO" },
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO", script_name = "registry-exchange-prod" },
  { name = "CONFIGURATION_REGISTRY_DO", class_name = "ConfigurationRegistryDO", script_name = "registry-prod" },
  { name = "ORACLE_REGISTRY_DO", class_name = "OracleRegistryDO", script_name = "registry-prod" },
  { name = "TOKEN_REGISTRY_DO", class_name = "TokenRegistryDO", script_name = "registry-prod" },
  { name = "VAULT_REGISTRY_DO", class_name = "VaultRegistryDO", script_name = "registry-prod" },
  { name = "YIELD_REGISTRY_DO", class_name = "YieldRegistryDO", script_name = "registry-prod" },
  { name = "VIEWS_DO", class_name = "ViewsDO", script_name = "data-dev" }
]

[env.prod.vars]
NX_ENV = "prod"
VERSION = "v2"
KPIS_NAME = "KPIS_DO"
ACCOUNTS_NAME = "ACCOUNTS_DO"
VIEWS_NAME = "VIEWS_DO"
