main = "./src/index.ts"
compatibility_date = "2022-11-11"
account_id = "274f86c6dcfbb77c09e49e86d101c753"

workers_dev = true
node_compat = true
minify = true
logpush = true

tsconfig = "tsconfig.json"

[env.prod]
name = "api-prod"
route = { pattern = "data.notional.finance", custom_domain = true }
r2_buckets = [
  { binding = "ACCOUNT_CACHE_R2", bucket_name = "account-cache-r2", preview_bucket_name = "account-cache-r2-dev" },
]

[env.prod.vars]
NX_ENV = "prod"