main = "./src/index.ts"
compatibility_date = "2022-11-11"
account_id = "274f86c6dcfbb77c09e49e86d101c753"

workers_dev = true
node_compat = true
minify = true
logpush = true

tsconfig = "tsconfig.json"

[env.prod]
name = "api-prod"
route = { pattern = "api.notional.finance", custom_domain = true }

[env.prod.vars]
NX_ENV = "prod"