main = "./src/index.ts"
compatibility_date = "2022-11-11"
account_id = "274f86c6dcfbb77c09e49e86d101c753"

workers_dev = true
node_compat = true
minify = true
usage_model = "bundled"
tsconfig = "tsconfig.json"

[[migrations]]
tag = "v1"
new_classes = ["KPIsDO"]

[[migrations]]
tag = "v2"
new_classes = ["AccountsDO"]

[env.local]
name = "api-local"
minify = false
durable_objects.bindings = [
  { name = "KPIS_DO", class_name = "KPIsDO" },
  { name = "ACCOUNTS_DO", class_name = "AccountsDO" }
]

[env.local.vars]
NX_ENV = "local"
VERSION = "v2"
KPIS_NAME = "KPIS_DO"
ACCOUNTS_NAME = "ACCOUNTS_DO"

[env.dev]
name = "api-dev"
route = { pattern = "data-dev.notional.finance", custom_domain = true }
durable_objects.bindings = [
  { name = "KPIS_DO", class_name = "KPIsDO" },
  { name = "ACCOUNTS_DO", class_name = "AccountsDO" }
]

[env.dev.vars]
NX_ENV = "dev"
VERSION = "v2"
KPIS_NAME = "KPIS_DO"
ACCOUNTS_NAME = "ACCOUNTS_DO"

[env.prod]
name = "api"
route = { pattern = "data.notional.finance", custom_domain = true }
durable_objects.bindings = [
  { name = "KPIS_DO", class_name = "KPIsDO" },
  { name = "ACCOUNTS_DO", class_name = "AccountsDO" }
]

[env.prod.vars]
NX_ENV = "prod"
VERSION = "v2"
KPIS_NAME = "KPIS_DO"
ACCOUNTS_NAME = "ACCOUNTS_DO"