main = "./src/index.ts"
compatibility_date = "2022-11-11"
account_id = "274f86c6dcfbb77c09e49e86d101c753"

workers_dev = true
node_compat = true
minify = true
logpush = true

tsconfig = "tsconfig.json"

[env.dev]
name = "api-dev"
route = { pattern = "data-dev.notional.finance", custom_domain = true }
durable_objects.bindings = [
  { name = "EXCHANGE_REGISTRY_DO", class_name = "ExchangeRegistryDO", script_name = "registry-exchanges-dev" },
  { name = "ORACLE_REGISTRY_DO", class_name = "OracleRegistryDO", script_name = "registry-oracles-dev" },
  { name = "CONFIGURATION_REGISTRY_DO", class_name = "ConfigurationRegistryDO", script_name = "registry-configuration-dev" },
  { name = "TOKEN_REGISTRY_DO", class_name = "TokenRegistryDO", script_name = "registry-tokens-dev" },
  { name = "VAULT_REGISTRY_DO", class_name = "VaultRegistryDO", script_name = "registry-vaults-dev" },
  { name = "VIEWS_DO", class_name = "ViewsDO", script_name = "data-dev" },
  { name = "ACCOUNTS_REGISTRY_DO", class_name = "RegistryClientDO", script_name = "accounts-dev" }
]
r2_buckets = [
  { binding = "ACCOUNT_CACHE_R2", bucket_name = "account-cache-r2", preview_bucket_name = "account-cache-r2-dev" },
]

[env.dev.vars]
NX_ENV = "dev"
# This is version that defines the durable object to retreive, increment it to reset
# the durable object to a clean version
VERSION = "v1"

[env.prod]
name = "api"
route = { pattern = "data.notional.finance", custom_domain = true }
r2_buckets = [
  { binding = "VIEW_CACHE_R2", bucket_name = "view-cache-r2", preview_bucket_name = "view-cache-r2-dev" },
]

[env.prod.vars]
NX_ENV = "prod"
VERSION = "v1"
VIEWS_NAME = "VIEWS_DO"