name: Deploy Tenderly Actions
on:
  push:
    branches:
      - v3/prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy All Workers
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sh
      - run: tenderly login --access-key ${{ secrets.TENDERLY_API_KEY }}
      - name: Deploy Actions
        shell: bash
        run: apps/deployTenderly.sh