name: GCP Deploy
on:
  push:
    branches:
      - v3/prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
    - run: yarn install --frozen-lockfile
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
    - name: Authenticate with GCP
      run: gcloud auth activate-service-account --key-file=${{ secrets.GCLOUD_SERVICE_KEY }}
    - name: Configure gcloud
      run: gcloud config set project ${{ secrets.GCLOUD_PROJECT_ID }}
    - name: Deploy Data Service
      shell: bash
      working-directory: gcp/data-service
      run: ./deploy.sh
    - name: Deploy Vault APY
      shell: bash
      working-directory: gcp/vault-apy
      run: ./deploy.sh
