name: deploy-arbitrum
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose an environment to deploy to: <arb>'
        required: true
        default: 'arb'
  push:
    branches:
      - v3/main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'arb' }}
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Build Web
        run: yarn nx build web --parallel
        env:
          NX_CONTACT_EMAIL: ${{ secrets.NX_CONTACT_EMAIL }}
          NX_DD_APP_ID: ${{ secrets.NX_DD_APP_ID }}
          NX_DD_CLIENT_TOKEN: ${{ secrets.NX_DD_CLIENT_TOKEN }}
          NX_DD_BASE_URL: ${{ secrets.NX_DD_BASE_URL }}
          NX_DD_SITE: ${{ secrets.NX_DD_SITE }}
          NX_APP_URL: ${{ secrets.NX_APP_URL }}
          NX_DATA_URL: ${{ secrets.NX_DATA_URL }}
          NX_SEGMENT_KEY: ${{ secrets.NX_SEGMENT_KEY }}
          NX_ENV: ${{ github.event.inputs.environment || 'arb' }}
          NX_COMMIT_REF: ${{ github.sha }}
      - name: Publish Dev
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: notional-web-${{ github.event.inputs.environment || 'arb' }}
          directory: dist/apps/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}